# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - v5-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # Required for requesting Azure JWT
      contents: read       # Required for actions/checkout

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build app (if build script exists)
        run: npm run build --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E5CCB0738A71491092A0902A354E9936 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7BF07A7ACB134A5F958D2196BBA59F3F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E80C2C5B95D54D0D850DE19F5055A1F8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'v5-backend'
          slot-name: 'Production'
          package: .
